### PR TITLE
Changed release archive to be version-agnostic, so that it is possibl…

### PR DESCRIPTION
**Pull request by jgebal**
…e to download and install the most recent version using `github/latest release link

### CODE REVIEW

**Comment by Pazus** [comment]
What is the name of the archive now?

**Comment by jgebal** [comment]
It's called `utPLSQL` now

**Comment by Pazus** [comment]
Could you show an URL how it will look like?
BTW:
https://github.com/facebook/react/releases

**Comment by jgebal** [comment]
I've found a way to download latest release without need to have the release file version-agnostic.
```bash
file_type='zip' # either 'zip' or 'gz' is availiable
download_url=`curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest | /usr/bin/awk '/browser_download_url/ { print $2 }' | grep ".${file_type}" | /usr/bin/sed 's/"//g'`
# echo ${download_url} # for debugging purposes
curl -LOk ${download_url}
```

**Comment by jgebal** [comment]
Since we don't need to make files version-agnostic to make them downloadable, I'm closing this PR.

**Pull request closed without merging**
