### PR TITLE
Implemented suite failure if setup procedure fails

### PR DESCRIPTION
**Pull request by Pazus**
Implemented suite failure if setup procedure fails
Looking for idea what to do when suite's teardown procedure fails

### CODE REVIEW

**Comment by Pazus** [comment]
addresses #137

**Comment by Pazus** [comment]
Don't merge for now. I implemented that before I read @jgebal comment.

**Comment by jgebal** [comment]
I think we should drop this PR.

**Comment by Pazus** [comment]
Need another solution and rewrite

**Pull request closed without merging**
