### PR TITLE
Feature/12ccoverage doc

### PR DESCRIPTION
**Pull request by lwasylow**
Updating Documentation regarding extended coverage

### CODE REVIEW

**Comment by jgebal** [comment]
Looking at the images:
Where did the:
...lines missed. **tr> <** 
come from?
It's showing in the header line of `extended_coverage_html_summary.png`?

**Comment by lwasylow** [comment]
Ah.. Trigger happy to push through so missed. I have taken out some things from html manually as first lines were at 0% in my sample i had. Will get that corrected and run tests on one test to get a nice result.

**Comment by jgebal** [comment]
So nothing wrong with the code itself then?

**Comment by lwasylow** [comment]
No it was just sample for whole ut3 schema so I removed some tr manually to make it more visible. I have rerun code for a one file now so it looks nicer on screenshot but code is OK.

**Pull request merged**
