### PR TITLE
bag fix

### PR DESCRIPTION
**Pull request by Mikhail5544**
source bag:
ORA-06512: на  "SYS.DBMS_LOB", line 1146
ORA-06512: на  "UT3.UT_EXECUTABLE", line 88
ORA-06512: на  "UT3.UT_EXECUTABLE", line 135
ORA-06512: на  "UT3.UT_EXECUTABLE", line 65
ORA-06512: на  "UT3.UT_TEST", line 76
ORA-06512: на  "UT3.UT_SUITE_ITEM", line 48
ORA-06512: на  "UT3.UT_SUITE", line 74
ORA-06512: на  "UT3.UT_RUN", line 41
ORA-06512: на  "UT3.UT_SUITE_ITEM", line 48
ORA-06512: на  "UT3.UT_RUNNER", line 34

ORA-06502: PL/SQL:  ошибка числа или значения

### CODE REVIEW

**Comment by jgebal** [comment]
It looks good. Thank you @Mikhail5544 
Would you be able to create a Unit Test to reproduce the issue and prove that the fix is working?

**Comment by jgebal** [comment]
@Mikhail5544 if you need any support in writing tests, reach out to me or @Pazus , we will be glad to help

**Comment by Mikhail5544** [comment]
@Pazus helped me with writing UT. Please, review it. :)

**Comment by jgebal** [comment]
Nice solution.
It would be best to see more of our tests rewritten to use the framework to test itself.

**Comment by jgebal** [comment]
You will need to update your branch from main develop as there were some other changes and it can't be merged. Can you do that?
I'd like this change to be included in the beta release.

**Comment by Pazus** [comment]
I've updated the branch using web.

**Comment by Pazus** [comment]
Approved. Will merge after successful build.
Thank you @Mikhail5544 for the contribution and a well defined change!

**Comment by jgebal** [comment]
Great work. Thanks for collaborating on it.

**Pull request merged**
