### PR TITLE
Feature - Documenation Framework

### PR DESCRIPTION
**Pull request by rlove**
What this pull request is:
  - PERL Script to generate documentation, using NaturalDocs
  - NaturalDocs moved to SubModule and updated to a version that handles cross platform issues, the original copy did not handle.
  - PERL script also convert markdown to html fragments or pages, and allows these to be linked to the documentation.   Allowing  common content such as CONTRIBUTING.MD to be in both places as one source.
  - Has Several empty documents and partial documentation that will need to be updated.    
  - Covers Issue #58

What this pull request is not:  
  - Complete Documentation
  - Roadmap for all documentation.
  - Automatic updating of published documentation when code is merged.

### CODE REVIEW

**Comment by Shoelace** [comment]
instead of using perl IPC.. can you not just
```do '../tools/ndocs/NaturalDocs' ```

see http://perldoc.perl.org/functions/do.html

**Comment by rlove** [comment]
When changing the language on .travis.yml file from BASH to PERL it changed the cache location on travis-ci.org side.      The error in the build is due to [not having access to the secure environment variable](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) to download oracle and cache it.    Once merged it will have access and cache the content with the perl systems.

I have travis-ci setup for my repository. 
https://travis-ci.org/rlove/utPLSQL  
Where the build was successful because it had access to the env variable.

**Comment by rlove** [comment]
@Shoelace I have tried to get `do` command to work but it fails to execute NaturalDocs.pl without error.

```
{
	 local @ARGV = qw<      
		  -i ../ 
		  -o HTML ../docs/ 
		  -p ./project 
		  -xi ../.travis 
		  -xi ../examples 
		  -xi ../lib 
		  -xi ../tools 
		  -xi ../build 
		  -r
		  >;	  
     do '../tools/ndocs/NaturalDocs.pl';
    }
```

Do you have any ideas?

**Comment by rlove** [comment]
I manually created the gh-pages branch which contains the generated documentation which is a result of this pull request.
https://utplsql.github.io/utPLSQL/version3/latest/index.html

I will auto upload it in a future pull request.

**Pull request merged**
