### PR TITLE
Tests were skipped if package was invalid

### LINKED ISSUE #192: annotation parser fails if any package in parsed schema is invalid.
When any of the packages in schema being parsed is not valid (has syntax error), then parser fails due to the dbms_preporcessor throwing an exception.

### PR DESCRIPTION
**Pull request by Pazus**
If a package is invalid and contains suite level hooks then tests were skipped with no failure. No all tests mark as failed.
This might fix #192 

What's done:
1) refactored us_suite_item child types, made procedure call to `do_execute` final and defined at the `ut_suite_item_level`
2) changed the order of calling event and setting start_time of an item to be the same across every child. Start and finish events are called even if the item is ignored, For ignored items end_time = start_time.
3) If you have a package with "before"/"after" suite-level hooks and the spec is invalid, then `ut_executable` of first "before" hook leads to the exeption. This should mark all the tests in the suite marked as failed. To do this if the suite is not "valid" the loop is added to iterate through `ut_test` items as they are also going to fail on `is_valid` procedure.

### CODE REVIEW

**Comment by Pazus** [comment]
also address #137

**Comment by Pazus** [comment]
aldo #139

**Comment by jgebal** [comment]
Can you explain how is this change addressing all the mentioned issues?

How will the executor behave now when we have:
- A test package without body
- A test package with invalid body
- A test package with invalid package spec
- A test package that is raising an exception in beforeall
- A test package that is raising an exception in afterall
- A test package that is raising an exception in beforeeach
- A test package that is raising an exception in aftereach
- A test package that is raising an exception in test

Also, what will happen if before, after or test procedure is issuing a commit?

**Comment by Pazus** [comment]
I should have written better description of the change. Edited the initial post.
What we corrently have:

**Comment by Pazus** [comment]
@jgebal We need to agree on the right behavior for `beforeall`, `afterall`, `beforeeach` and when there is no body

**Comment by Pazus** [comment]
New behavior:
A test package without body - each test is reported as failed
A test package with invalid body - each test is reported as failed
A test package with invalid package spec - *tests are skipped*. Only valid specifications are parsed for annotations.
A test package that is raising an exception in beforeall - each test is reported as failed
A test package that is raising an exception in afterall - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Does not remove room when it has content
  Raises exception when null room name given
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content (FAILED - 2)
  Raises exception when null room name given (FAILED - 3)
 
Failures:
 
  1) remove_empty_room
        
        error: Afterall procedure failed: 
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 29
               ORA-06512: at line 6
       
  2) room_with_content
        
        error: Afterall procedure failed: 
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 29
               ORA-06512: at line 6
       
  3) null_room_name
        
        error: Afterall procedure failed: 
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 29
               ORA-06512: at line 6
       
Finished in ,030293 seconds
3 tests, 0 failed, 3 errored, 0 ignored
```
A test package that is raising an exception in beforeeach - each test is reported as failed
A test package that is raising an exception in aftereach - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content
  Does not remove room when it has content (FAILED - 2)
  Raises exception when null room name given
  Raises exception when null room name given (FAILED - 3)
 
Failures:
 
  1) remove_empty_room
        
        error: Aftereach procedure failed:
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 40
               ORA-06512: at line 6
       
  2) room_with_content
        
        error: Aftereach procedure failed:
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 40
               ORA-06512: at line 6
       
  3) null_room_name
        
        error: Aftereach procedure failed:
               ORA-20001: asd
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 40
               ORA-06512: at line 6
       
Finished in ,052271 seconds
3 tests, 0 failed, 3 errored, 0 ignored
```
A test package that is raising an exception in test - the test is marked as failed

**Comment by Pazus** [comment]
New behavior:
A test package without body - each test is reported as failed
A test package with invalid body - each test is reported as failed
A test package with invalid package spec - *tests are skipped*. Only valid specifications are parsed for annotations.
A test package that is raising an exception in beforeall - each test is reported as failed
A test package that is raising an exception in afterall - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Does not remove room when it has content
  Raises exception when null room name given
 
Warnings:
 
Afterall procedure failed: 
ORA-20001: EXCEPTION TEST
ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 34
ORA-06512: at line 6
 
Finished in ,03872 seconds
3 tests, 0 failed, 0 errored, 0 ignored. 1 warning(s)
```
A test package that is raising an exception in beforeeach - each test is reported as failed
A test package that is raising an exception in aftereach - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Does not remove room when it has content
  Raises exception when null room name given
 
Warnings:
 
Aftereach procedure failed:
ORA-20001: EXCEPTION TEST
ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
ORA-06512: at line 6
 
Aftereach procedure failed:
ORA-20001: EXCEPTION TEST
ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
ORA-06512: at line 6
 
Aftereach procedure failed:
ORA-20001: EXCEPTION TEST
ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
ORA-06512: at line 6
 
Finished in ,046337 seconds
3 tests, 0 failed, 0 errored, 0 ignored. 3 warning(s)
```
A test package that is raising an exception in test - the test is marked as failed

**Comment by Pazus** [comment]
What currently I don't like is that warnings are not connected to the place were error occured. Should be improved.

**Comment by jgebal** [comment]
I think that if beforeall/beforeeach fails, we should fail the tests that depend not hose blocks.
For aftereach, we should also fail test.To do that, we need however to report on the test execution *after* the afteraeach block was executed for that test.


If the afterall block fails, we should not fail the tests that already have executed successfully.
Instead, we could report exceptions raised in before/after blocks on test/suite level.

To do that:
- test would need to have placeholder for exceptions
- suite would need to have placeholder for exceptions
- each dynamic block (before/exec/after) invoked in test would populate exceptions list in the `ut_test` object
- each dynamic block (before/after) invoked in suite, would populate exceptions list in the `ut_suite` object
Reporters should include exceptions outputs from both suite level and test level.
If you look at the XSD for [JUnit](https://gist.github.com/kuzuha/232902acab1344d6b578) you will notce that it is supporting stderr and stdout on suite level.

Teamcity reporter should indicate progress using the after_test hook.
I think we should remove some of the reporter hooks. They give lots of flexibility, but also bring confusion on when to use which hook use them.
Maybe hooks before/after run/suite/tests (6 hooks) would be sufficient?

**Comment by jgebal** [comment]
I like the new behaviour though not sure about the way it's implemented. Need to think about ways to make it cleaner.

**Comment by Pazus** [comment]
Behavior after recent changes:
New behavior:
A test package without body - each test is reported as failed
A test package with invalid body - each test is reported as failed
A test package with invalid package spec - *tests are skipped*. Only valid specifications are parsed for annotations.
A test package that is raising an exception in beforeall - each test is reported as failed
A test package that is raising an exception in afterall - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Does not remove room when it has content
  Raises exception when null room name given
 
Warnings:
 
  1) test_remove_rooms_by_name - Afterall procedure failed: 
       ORA-20001: Test exception
       ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 35
       ORA-06512: at line 6
 
Finished in ,044902 seconds
3 tests, 0 failed, 0 errored, 0 ignored. 1 warning(s)
```
A test package that is raising an exception in beforeeach - each test is reported as failed
A test package that is raising an exception in aftereach - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it
  Does not remove room when it has content
  Raises exception when null room name given
 
Warnings:
 
  1) test_remove_rooms_by_name - Aftereach procedure failed:
       ORA-20001: Test exception
       ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
       ORA-06512: at line 6
 
  2) test_remove_rooms_by_name - Aftereach procedure failed:
       ORA-20001: Test exception
       ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
       ORA-06512: at line 6
 
  3) test_remove_rooms_by_name - Aftereach procedure failed:
       ORA-20001: Test exception
       ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 31
       ORA-06512: at line 6
 
Finished in ,05071 seconds
3 tests, 0 failed, 0 errored, 0 ignored. 3 warning(s)
```
A test package that is raising an exception in test - the test is marked as failed
```
Remove rooms by name
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content
  Raises exception when null room name given
 
Failures:
 
  1) remove_empty_room
        
        error: ORA-20001: Test exception
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 48
               ORA-06512: at line 6
       
Finished in ,035726 seconds
3 tests, 0 failed, 1 errored, 0 ignored.
```
A test package that is raising an exception in beforetest - each test is reported as failed
````
Remove rooms by name
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content
  Raises exception when null room name given
 
Failures:
 
  1) remove_empty_room
        
        error: ORA-20001: Test exception
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 39
               ORA-06512: at line 6
       
Finished in ,039346 seconds
3 tests, 0 failed, 1 errored, 0 ignored.
````
A test package that is raising an exception in aftertest - *each test is reported ok but then each is marked as failed*
```
Remove rooms by name
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content
  Raises exception when null room name given
 
Failures:
 
  1) remove_empty_room
        
        error: ORA-20001: Test exception
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 42
               ORA-06512: at line 6
       
Finished in ,045523 seconds
3 tests, 0 failed, 1 errored, 0 ignored.
```

**Comment by jgebal** [comment]
A small update to the description (in bold)
-----
A test package that is raising an exception in aftertest - **each test is reported as failed**
```
Remove rooms by name
  Removes a room without content in it (FAILED - 1)
  Does not remove room when it has content
  Raises exception when null room name given
 
Failures:
 
  1) remove_empty_room
        
        error: ORA-20001: Test exception
               ORA-06512: at "UT3.TEST_REMOVE_ROOMS_BY_NAME", line 42
               ORA-06512: at line 6
       
Finished in ,045523 seconds
3 tests, 0 failed, 1 errored, 0 ignored.
```

**Comment by jgebal** [comment]
I think the code is in a good shape to be merged.
Before merging however, it would be good to update the documentation. The comments on this PR are of a high value and I'm pretty sure, we will get many questions around how thins work in those cases. Having that documented seems to be the best option as we can refer to the doc at any time.

**Comment by Pazus** [comment]
Documented the behavior

**Pull request merged**
