### PR TITLE
Fix root tag for Sonar Unit Test reporter

### PR DESCRIPTION
**Pull request by rostskadat**
According to https://github.com/SonarQubeCommunity/sonar-generic-coverage#unit-tests-execution-results-report-format

### CODE REVIEW

**Comment by rostskadat** [comment]
This is a fix for #566

**Comment by jgebal** [comment]
The element is correct, as sonar changed the root element.
The link you provided states in readme file.
```
Deprecated since SonarQube 6.2 because the functionality was absorbed into SonarQube core.
```

utPLSQL v3 was released way after sonar 6.2
We decided to support new version instead of the legacy one.

**Comment by rostskadat** [comment]
OK

**Comment by rostskadat** [comment]
We'll update our local instalation.

BTW, thanks for the amazing package :)

**Comment by jgebal** [comment]
I would suggest creating a new reporter as a copy or better under this one.
That way you will not get impacted by changes done in future releases

**Pull request closed without merging**
