### PR TITLE
Reorganized test-users privileges

### PR DESCRIPTION
**Pull request by jgebal**

### CODE REVIEW

**Comment by lwasylow** [comment]
Since you working already in install I've noticed that uninstall got some error:
```
In command -
drop trigger ut_trigger_annotation_parsing
Error report -
ORA-04080: trigger 'UT_TRIGGER_ANNOTATION_PARSING' does not exist
```

**Comment by jgebal** [comment]
@lwasylow - is this on Travos or local error?
If local, did you install wirh trigger?

**Comment by lwasylow** [comment]
It's on Travis

**Comment by jgebal** [comment]
Odd.
Looking into Travis logs I see the trigger is getting dropped successfully.
https://travis-ci.org/utPLSQL/utPLSQL/jobs/547976502#L2275
https://travis-ci.org/utPLSQL/utPLSQL/jobs/547960863#L2270

The only thing that is not getting dropped cleanly is a synonym (as it doesn't exist at that time yet)

**Comment by lwasylow** [comment]
Line 2714 of log https://travis-ci.org/utPLSQL/utPLSQL/jobs/547976502
Error starting at line : 177 File @ /home/travis/build/utPLSQL/utPLSQL/source/uninstall_objects.sql
In command -
drop trigger ut_trigger_annotation_parsing
Error report -
ORA-04080: trigger 'UT_TRIGGER_ANNOTATION_PARSING' does not exist

**Comment by jgebal** [comment]
@lwasylow - this one is resolved now - the drop trigger was there twice in uninstall script.
Maybe we should make uninstall fail on any error in Travis just to make sure it always works without issues.

**Comment by lwasylow** [comment]
Yes agree, it should fail in build env.

**Comment by jgebal** [comment]
This is done as part of #953
So I'm merging this PR.

**Pull request merged**
